import type { NextPage } from 'next'
import Head from 'next/head'
import Center from '../components/Center'
import Player from '../components/Player'
import Sidebar from '../components/Sidebar'
import PlaylistContextProvider from '../contexts/PlaylistContext'
import SongContextProvider from '../contexts/SongContext'

const Home: NextPage = () => {
	return (
		// TODO: this div has overflow-hidden, but let's see how it goes
		<div className='bg-black h-screen'>
			<PlaylistContextProvider>
				<SongContextProvider>
					<Head>
						<title>Spotify 2.0</title>
						<meta name='description' content='Generated by create next app' />
						<link rel='icon' href='/favicon.ico' />
					</Head>

					<main className='flex'>
						<Sidebar />
						<Center />
					</main>

					<div className='sticky bottom-0 text-white'>
						<Player />
					</div>
				</SongContextProvider>
			</PlaylistContextProvider>
		</div>
	)
}

export default Home
