import type { NextPage } from 'next'
import Head from 'next/head'
import Center from '../components/Center'
import Sidebar from '../components/Sidebar'
import PlaylistContextProvider from '../contexts'

const Home: NextPage = () => {
	return (
		// TODO: this div has overflow-hidden, but let's see how it goes
		<div className='bg-black h-screen'>
			<Head>
				<title>Spotify 2.0</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className='flex'>
				<PlaylistContextProvider>
					<Sidebar />
					<Center />
				</PlaylistContextProvider>
			</main>

			<div>{/* Player */}</div>
		</div>
	)
}

export default Home
